pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }

    triggers { pollSCM('* * * * *') }

    stages {
        stage('Checkout repo') {
            steps {
                git url: 'https://github.com/seabornlee/member-service.git', branch: 'master'
            }
        }

        stage('Test') {
            steps {
                sh './mvnw test'
            }
        }

        stage('Package') {
            steps {
                sh './mvnw package'
            }
        }

        stage('Gen image') {
            steps {
                sh 'docker build . -t 192.168.1.103:5000/member-service:0.0.$BUILD_NUMBER'
            }
        }
    }
}