pipeline {
    agent any

    triggers { pollSCM('* * * * *') }

    stages {
        stage('Checkout repo') {
            steps {
                git url: 'https://github.com/seabornlee/member-service.git', branch: 'master'
            }
        }

        stage('Test') {
            steps {
                sh './mvnw test'
                junit 'target/surefire-reports/*.xml'
            }
        }

        stage('Package') {
            steps {
                sh './mvnw clean package -Dunit-tests.skip=true -Dintegration-tests.skip=true'
            }
        }

        stage('Gen image') {
            steps {
                sh 'docker build . -t 192.168.1.103:5000/member-service:0.0.$BUILD_NUMBER'
            }
        }
    }
}