node {
    stage('Checkout repo') {
        git url: 'https://github.com/seabornlee/member-service.git',
            branch: 'master'
    }

    stage('Test') {
        sh './mvnw test'
    }
    
    stage('Build web') {
        sh './mvnw build'
    }

    stage('Gen image') {
        sh 'docker build . -t 127.0.0.1:5000/member-service:0.0.$BUILD_NUMBER'
    }
}